export const habitaciones = [
  {
    id: 1,
    nombre: 'Individual',
    categoria: 'CONFORT',
    descripcion: 'Perfecta para viajeros solitarios que buscan comodidad y funcionalidad en un espacio acogedor. Incluye desayuno.',
    precio: 25,
    capacidad: '1 persona',
    cama: '1 cama individual',
    tamaño: '18 m²',
    imagenes: [
      'https://res.cloudinary.com/dltfsttr7/image/upload/v1760204466/IMG_4616_xg9lrj.jpg',
    ],
    amenidades: ['Wi-Fi gratis', 'TV cable', 'Baño privado', 'Escritorio', 'Caja fuerte', 'Desayuno incluido'],
  },
  {
    id: 2,
    nombre: 'Matrimonial',
    categoria: 'POPULAR',
    descripcion: 'Espacio elegante para parejas. Incluye desayuno.',
    precio: 41,
    capacidad: '2 personas',
    cama: '1 cama matrimonial',
    tamaño: '25 m²',
    imagenes: [
      'https://res.cloudinary.com/dltfsttr7/image/upload/v1760204509/IMG_4605_q6bvol.jpg',
    ],
  amenidades: ['Wi-Fi gratis', 'TV Smart', 'Baño privado', 'Aire acondicionado', 'Vista a la ciudad', 'Desayuno incluido'],
  },
  {
    id: 3,
    nombre: 'Doble cama',
    categoria: 'DOBLE',
    descripcion: 'Habitación con dos camas. Incluye desayuno.',
    precio: 45,
    capacidad: '2 personas',
    cama: '2 camas individuales',
    tamaño: '25 m²',
    imagenes: [
      'https://res.cloudinary.com/dltfsttr7/image/upload/v1760204555/IMG_4600_q2teiy.jpg',
    ],
  amenidades: ['Wi-Fi gratis', 'TV Smart', 'Baño privado', 'Aire acondicionado', 'Vista a la ciudad', 'Desayuno incluido'],
  },
  {
    id: 4,
    nombre: 'Triple',
    categoria: 'TRIPLE',
    descripcion: 'Habitación para tres personas. Incluye desayuno.',
    precio: 50,
    capacidad: '3 personas',
    cama: '3 camas individuales',
    tamaño: '30 m²',
    imagenes: [
      'https://res.cloudinary.com/dltfsttr7/image/upload/v1760204999/IMG_4183-HDR_gs5who.webp',
    ],
  amenidades: ['Wi-Fi gratis', 'TV Smart', 'Baño privado', 'Aire acondicionado', 'Desayuno incluido'],
  },
  {
    id: 5,
    nombre: 'Cuádruple',
    categoria: 'CUÁDRUPLE',
    descripcion: 'Habitación para cuatro personas. Incluye desayuno.',
    precio: 60,
    capacidad: '4 personas',
    cama: '4 camas individuales',
    tamaño: '35 m²',
    imagenes: [
      'https://res.cloudinary.com/dltfsttr7/image/upload/v1760204999/IMG_4183-HDR_gs5who.webp',
    ],
  amenidades: ['Wi-Fi gratis', 'TV Smart', 'Baño privado', 'Aire acondicionado', 'Desayuno incluido'],
  },
  {
    id: 6,
    nombre: 'Familiar',
    categoria: 'FAMILIA',
    descripcion: 'Habitación familiar. El precio es por persona ($15). Incluye desayuno.',
    precio: 15,
    capacidad: 'por persona',
    cama: 'Camas múltiples',
    tamaño: '45 m²',
    imagenes: [
      'https://res.cloudinary.com/dltfsttr7/image/upload/v1760204251/IMG_4163-HDR_ymaqov.webp',
    ],
    amenidades: ['Wi-Fi gratis', '2 TV Smart', 'Cocina pequeña', 'Sala amplia', 'Desayuno incluido', 'Juegos para niños', 'Balcón privado'],
  },
];

export const testimonios = [
  { nombre: 'María González', ubicacion: 'Quito, Ecuador', calificacion: 5, fecha: 'Hace 2 semanas', comentario: 'Excelente hotel en el centro de Loja. Las habitaciones son muy cómodas y limpias. El desayuno es delicioso, especialmente en la Cafetería Viviates. El personal es muy amable y atento. Definitivamente volveré.', avatar: 'MG' },
  { nombre: 'Carlos Ramírez', ubicacion: 'Cuenca, Ecuador', calificacion: 5, fecha: 'Hace 1 mes', comentario: 'Me hospedé por negocios y la experiencia fue perfecta. Excelente ubicación, Wi-Fi rápido, y las habitaciones muy bien equipadas. La Cafetería Viviates es lo mejor, no había probado un café tan bueno en mucho tiempo.', avatar: 'CR' },
  { nombre: 'Ana Martínez', ubicacion: 'Guayaquil, Ecuador', calificacion: 5, fecha: 'Hace 3 semanas', comentario: 'Estuvimos de vacaciones familiares y fue una experiencia maravillosa. La suite familiar es espaciosa y cómoda. El personal nos ayudó a organizar tours por la ciudad. Muy recomendado para familias.', avatar: 'AM' },
  { nombre: 'Roberto Silva', ubicacion: 'Lima, Perú', calificacion: 5, fecha: 'Hace 2 meses', comentario: 'Hotel impecable en todos los aspectos. Limpieza excelente, atención de primera, y el desayuno buffet es espectacular. La ubicación es perfecta para conocer Loja. Sin duda el mejor hotel de la ciudad.', avatar: 'RS' },
  { nombre: 'Laura Jiménez', ubicacion: 'Machala, Ecuador', calificacion: 5, fecha: 'Hace 1 semana', comentario: 'Hermoso hotel, las fotos no le hacen justicia. Las habitaciones son elegantes y muy cómodas. El restaurante tiene comida deliciosa y el café es increíble. El personal siempre dispuesto a ayudar. 100% recomendado.', avatar: 'LJ' },
  { nombre: 'Diego Torres', ubicacion: 'Loja, Ecuador', calificacion: 5, fecha: 'Hace 3 días', comentario: 'Hospedé a mis familiares que vinieron de visita y quedaron encantados. Excelente relación calidad-precio. El estacionamiento gratuito es un plus. La Cafetería Viviates ahora es mi favorito de la ciudad.', avatar: 'DT' },
];